<script lang="ts">
	import Option from '../option.svelte';

	interface CountryPresetAttributes {
		selected?: string;
		showflag?: boolean;
		showphone?: boolean;
	}

	const { selected, showflag = true, showphone = false }: CountryPresetAttributes = $props();

	export const countries = [
		{ n: 'Afghanistan', c: 'af', p: 93 },
		{ n: 'Albania', c: 'al', p: 355 },
		{ n: 'Algeria', c: 'dz', p: 213 },
		{ n: 'Andorra', c: 'ad', p: 376 },
		{ n: 'Angola', c: 'ao', p: 244 },
		{ n: 'Anguilla', c: 'ai', p: 1264 },
		{ n: 'Antigua and Barbuda', c: 'ag', p: 1268 },
		{ n: 'Argentina', c: 'ar', p: 54 },
		{ n: 'Armenia', c: 'am', p: 374 },
		{ n: 'Aruba', c: 'aw', p: 297 },
		{ n: 'Australia', c: 'au', p: 61 },
		{ n: 'Austria', c: 'at', p: 43 },
		{ n: 'Azerbaijan', c: 'az', p: 994 },
		{ n: 'Bahamas', c: 'bs', p: 1242 },
		{ n: 'Bahrain', c: 'bh', p: 943 },
		{ n: 'Bangladesh', c: 'bd', p: 880 },
		{ n: 'Barbados', c: 'bb', p: 1246 },
		{ n: 'Belarus', c: 'by', p: 375 },
		{ n: 'Belgium', c: 'be', p: 32 },
		{ n: 'Belize', c: 'bz', p: 501 },
		{ n: 'Benin', c: 'bj', p: 229 },
		{ n: 'Bhutan', c: 'bt', p: 975 },
		{ n: 'Bolivia', c: 'bo', p: 591 },
		{ n: 'Bosnia and Herzegovina', c: 'ba', p: 387 },
		{ n: 'Botswana', c: 'bw', p: 267 },
		{ n: 'Brazil', c: 'br', p: 55 },
		{ n: 'Brunei', c: 'bn', p: 673 },
		{ n: 'Bulgaria', c: 'bg', p: 359 },
		{ n: 'Burkina Faso', c: 'bf', p: 226 },
		{ n: 'Burundi', c: 'bi', p: 257 },
		{ n: 'Cambodia', c: 'kh', p: 855 },
		{ n: 'Cameroon', c: 'cm', p: 237 },
		{ n: 'Canada', c: 'ca', p: 1 },
		{ n: 'Cape Verde', c: 'cv', p: 238 },
		{ n: 'Caribbean Netherlands', c: 'bq', p: 599 },
		{ n: 'Central African Republic', c: 'cf', p: 236 },
		{ n: 'Chad', c: 'td', p: 235 },
		{ n: 'Chile', c: 'cl', p: 56 },
		{ n: 'China', c: 'cn', p: 86 },
		{ n: 'Colombia', c: 'co', p: 57 },
		{ n: 'Comoros', c: 'km', p: 269 },
		{ n: 'Congo', c: 'cg', p: 242 },
		{ n: 'Costa Rica', c: 'cr', p: 506 },
		{ n: 'Côte d’Ivoire', c: 'ci', p: 225 },
		{ n: 'Croatia', c: 'hr', p: 385 },
		{ n: 'Cuba', c: 'cu', p: 53 },
		{ n: 'Curaçao', c: 'cw', p: 5999 },
		{ n: 'Cyprus', c: 'cy', p: 357 },
		{ n: 'Czech Republic', c: 'cz', p: 420 },
		{ n: 'Democratic Republic of the Congo', c: 'cd', p: 243 },
		{ n: 'Denmark', c: 'dk', p: 45 },
		{ n: 'Djibouti', c: 'dj', p: 253 },
		{ n: 'Dominica', c: 'dm', p: 1767 },
		{ n: 'Dominican Republic', c: 'do', p: 1809 },
		{ n: 'Ecuador', c: 'ec', p: 593 },
		{ n: 'Egypt', c: 'eg', p: 20 },
		{ n: 'El Salvador', c: 'sv', p: 503 },
		{ n: 'Equatorial Guinea', c: 'gq', p: 240 },
		{ n: 'Eritrea', c: 'er', p: 291 },
		{ n: 'Estonia', c: 'ee', p: 372 },
		{ n: 'Ethiopia', c: 'et', p: 251 },
		{ n: 'Fiji', c: 'fj', p: 679 },
		{ n: 'Finland', c: 'fi', p: 358 },
		{ n: 'France', c: 'fr', p: 33 },
		{ n: 'Gabon', c: 'ga', p: 241 },
		{ n: 'Gambia', c: 'gm', p: 220 },
		{ n: 'Georgia', c: 'ge', p: 995 },
		{ n: 'Germany', c: 'de', p: 49 },
		{ n: 'Ghana', c: 'gh', p: 233 },
		{ n: 'Greece', c: 'gr', p: 30 },
		{ n: 'Grenada', c: 'gd', p: 1473 },
		{ n: 'Guatemala', c: 'gt', p: 502 },
		{ n: 'Guinea', c: 'gn', p: 224 },
		{ n: 'Guinea-Bissau', c: 'gw', p: 245 },
		{ n: 'Guyana', c: 'gy', p: 592 },
		{ n: 'Haiti', c: 'ht', p: 509 },
		{ n: 'Holy See', c: 'va', p: 379 },
		{ n: 'Honduras', c: 'hn', p: 504 },
		{ n: 'Hungary', c: 'hu', p: 36 },
		{ n: 'Iceland', c: 'is', p: 354 },
		{ n: 'India', c: 'in', p: 91 },
		{ n: 'Indonesia', c: 'id', p: 62 },
		{ n: 'Iran', c: 'ir', p: 98 },
		{ n: 'Iraq', c: 'iq', p: 964 },
		{ n: 'Ireland', c: 'ie', p: 353 },
		{ n: 'Israel', c: 'il', p: 972 },
		{ n: 'Italy', c: 'it', p: 39 },
		{ n: 'Jamaica', c: 'jm', p: 1876 },
		{ n: 'Japan', c: 'jp', p: 81 },
		{ n: 'Jordan', c: 'jo', p: 962 },
		{ n: 'Kazakhstan', c: 'kz', p: 7 },
		{ n: 'Kenya', c: 'ke', p: 254 },
		{ n: 'Kiribati', c: 'ki', p: 686 },
		{ n: 'Kuwait', c: 'kw', p: 965 },
		{ n: 'Kyrgyzstan', c: 'kg', p: 996 },
		{ n: 'Laos', c: 'la', p: 856 },
		{ n: 'Latvia', c: 'lv', p: 371 },
		{ n: 'Lebanon', c: 'lb', p: 961 },
		{ n: 'Lesotho', c: 'ls', p: 266 },
		{ n: 'Liberia', c: 'lr', p: 231 },
		{ n: 'Libya', c: 'ly', p: 218 },
		{ n: 'Liechtenstein', c: 'li', p: 423 },
		{ n: 'Lithuania', c: 'lt', p: 370 },
		{ n: 'Luxembourg', c: 'lu', p: 352 },
		{ n: 'Madagascar', c: 'mg', p: 261 },
		{ n: 'Malawi', c: 'mw', p: 265 },
		{ n: 'Malaysia', c: 'my', p: 60 },
		{ n: 'Maldives', c: 'mv', p: 960 },
		{ n: 'Mali', c: 'ml', p: 223 },
		{ n: 'Malta', c: 'mt', p: 356 },
		{ n: 'Marshall Islands', c: 'mh', p: 692 },
		{ n: 'Mauritania', c: 'mr', p: 222 },
		{ n: 'Mauritius', c: 'mu', p: 230 },
		{ n: 'Mexico', c: 'mx', p: 52 },
		{ n: 'Micronesia', c: 'fm', p: 691 },
		{ n: 'Moldova', c: 'md', p: 373 },
		{ n: 'Monaco', c: 'mc', p: 377 },
		{ n: 'Mongolia', c: 'mn', p: 976 },
		{ n: 'Montenegro', c: 'me', p: 382 },
		{ n: 'Montserrat', c: 'ms', p: 1664 },
		{ n: 'Morocco', c: 'ma', p: 212 },
		{ n: 'Mozambique', c: 'mz', p: 258 },
		{ n: 'Myanmar', c: 'mm', p: 95 },
		{ n: 'Namibia', c: 'na', p: 264 },
		{ n: 'Nauru', c: 'nr', p: 674 },
		{ n: 'Nepal', c: 'np', p: 977 },
		{ n: 'Netherlands', c: 'nl', p: 31 },
		{ n: 'New Zealand', c: 'nz', p: 64 },
		{ n: 'Nicaragua', c: 'ni', p: 505 },
		{ n: 'Niger', c: 'ne', p: 227 },
		{ n: 'Nigeria', c: 'ng', p: 234 },
		{ n: 'North Korea', c: 'kp', p: 850 },
		{ n: 'North Macedonia', c: 'mk', p: 389 },
		{ n: 'Norway', c: 'no', p: 47 },
		{ n: 'Oman', c: 'om', p: 968 },
		{ n: 'Pakistan', c: 'pk', p: 92 },
		{ n: 'Palau', c: 'pw', p: 680 },
		{ n: 'Palestine State', c: 'ps', p: 970 },
		{ n: 'Panama', c: 'pa', p: 507 },
		{ n: 'Papua New Guinea', c: 'pg', p: 675 },
		{ n: 'Paraguay', c: 'py', p: 595 },
		{ n: 'Peru', c: 'pe', p: 51 },
		{ n: 'Philippines', c: 'ph', p: 63 },
		{ n: 'Poland', c: 'pl', p: 58 },
		{ n: 'Portugal', c: 'pt', p: 351 },
		{ n: 'Puerto Rico', c: 'pr', p: 1787 },
		{ n: 'Qatar', c: 'qa', p: 974 },
		{ n: 'Romania', c: 'ro', p: 40 },
		{ n: 'Russia', c: 'ru', p: 7 },
		{ n: 'Rwanda', c: 'rw', p: 250 },
		{ n: 'Saint Kitts and Nevis', c: 'kn', p: 1869 },
		{ n: 'Saint Lucia', c: 'lc', p: 1758 },
		{ n: 'Saint Vincent and the Grenadines', c: 'vc', p: 1784 },
		{ n: 'Samoa', c: 'ws', p: 685 },
		{ n: 'San Marino', c: 'sm', p: 378 },
		{ n: 'Sao Tome and Principe', c: 'st', p: 239 },
		{ n: 'Saudi Arabia', c: 'sa', p: 966 },
		{ n: 'Senegal', c: 'sn', p: 221 },
		{ n: 'Serbia', c: 'rs', p: 381 },
		{ n: 'Seychelles', c: 'sc', p: 248 },
		{ n: 'Sierra Leone', c: 'sl', p: 232 },
		{ n: 'Singapore', c: 'sg', p: 65 },
		{ n: 'Sint Maarten', c: 'sx', p: 1721 },
		{ n: 'Slovakia', c: 'sk', p: 421 },
		{ n: 'Slovenia', c: 'si', p: 386 },
		{ n: 'Solomon Islands', c: 'sb', p: 677 },
		{ n: 'Somalia', c: 'so', p: 252 },
		{ n: 'South Africa', c: 'za', p: 27 },
		{ n: 'South Korea', c: 'kr', p: 82 },
		{ n: 'South Sudan', c: 'ss', p: 211 },
		{ n: 'Spain', c: 'es', p: 34 },
		{ n: 'Sri Lanka', c: 'lk', p: 94 },
		{ n: 'Sudan', c: 'sd', p: 249 },
		{ n: 'Suriname', c: 'sr', p: 597 },
		{ n: 'Sweden', c: 'se', p: 46 },
		{ n: 'Switzerland', c: 'ch', p: 41 },
		{ n: 'Syria', c: 'sy', p: 963 },
		{ n: 'Tajikistan', c: 'tj', p: 992 },
		{ n: 'Tanzania', c: 'tz', p: 255 },
		{ n: 'Thailand', c: 'th', p: 66 },
		{ n: 'Timor-Leste', c: 'tl', p: 670 },
		{ n: 'Togo', c: 'tg', p: 228 },
		{ n: 'Tonga', c: 'to', p: 676 },
		{ n: 'Trinidad and Tobago', c: 'tt', p: 1868 },
		{ n: 'Tunisia', c: 'tn', p: 216 },
		{ n: 'Turkey', c: 'tr', p: 90 },
		{ n: 'Turkmenistan', c: 'tm', p: 993 },
		{ n: 'Tuvalu', c: 'tv', p: 688 },
		{ n: 'Uganda', c: 'ug', p: 256 },
		{ n: 'Ukraine', c: 'ua', p: 380 },
		{ n: 'United Arab Emirates', c: 'ae', p: 971 },
		{ n: 'United Kingdom', c: 'gb', p: 44 },
		{ n: 'United States of America', c: 'us', p: 1 },
		{ n: 'Uruguay', c: 'uy', p: 598 },
		{ n: 'Uzbekistan', c: 'uz', p: 998 },
		{ n: 'Vanuatu', c: 'vu', p: 678 },
		{ n: 'Venezuela', c: 've', p: 58 },
		{ n: 'Vietnam', c: 'vn', p: 84 },
		{ n: 'Yemen', c: 'ye', p: 967 },
		{ n: 'Zambia', c: 'zm', p: 260 },
		{ n: 'Zimbabwe', c: 'zw', p: 26 }
	];
</script>

{#each countries as country}
	<Option value={country.c} selected={selected?.toLowerCase() === country.c}>
		{#snippet prefix()}
			{#if showflag}
				<img src="https://flagcdn.com/w20/{country.c}.png" width="20" alt={country.n} />
			{/if}
		{/snippet}

		{country.n}

		{#snippet suffix()}
			{#if showphone}
				<span style:margin-left="auto">+{country.p}</span>
			{/if}
		{/snippet}
	</Option>
{/each}
