<script lang="ts">
	import Option from '../option.svelte';

	interface CountryPresetAttributes {
		selected?: string;
	}

	const { selected }: CountryPresetAttributes = $props();

	export const countries = [
		{ c: 'ad', n: 'Andorra' },
		{ c: 'ae', n: 'United Arab Emirates' },
		{ c: 'af', n: 'Afghanistan' },
		{ c: 'ag', n: 'Antigua and Barbuda' },
		{ c: 'ai', n: 'Anguilla' },
		{ c: 'al', n: 'Albania' },
		{ c: 'am', n: 'Armenia' },
		{ c: 'ao', n: 'Angola' },
		{ c: 'aq', n: 'Antarctica' },
		{ c: 'ar', n: 'Argentina' },
		{ c: 'as', n: 'American Samoa' },
		{ c: 'at', n: 'Austria' },
		{ c: 'au', n: 'Australia' },
		{ c: 'aw', n: 'Aruba' },
		{ c: 'ax', n: 'Åland Islands' },
		{ c: 'az', n: 'Azerbaijan' },
		{ c: 'ba', n: 'Bosnia and Herzegovina' },
		{ c: 'bb', n: 'Barbados' },
		{ c: 'bd', n: 'Bangladesh' },
		{ c: 'be', n: 'Belgium' },
		{ c: 'bf', n: 'Burkina Faso' },
		{ c: 'bg', n: 'Bulgaria' },
		{ c: 'bh', n: 'Bahrain' },
		{ c: 'bi', n: 'Burundi' },
		{ c: 'bj', n: 'Benin' },
		{ c: 'bl', n: 'Saint Barthélemy' },
		{ c: 'bm', n: 'Bermuda' },
		{ c: 'bn', n: 'Brunei' },
		{ c: 'bo', n: 'Bolivia' },
		{ c: 'bq', n: 'Caribbean Netherlands' },
		{ c: 'br', n: 'Brazil' },
		{ c: 'bs', n: 'Bahamas' },
		{ c: 'bt', n: 'Bhutan' },
		{ c: 'bv', n: 'Bouvet Island' },
		{ c: 'bw', n: 'Botswana' },
		{ c: 'by', n: 'Belarus' },
		{ c: 'bz', n: 'Belize' },
		{ c: 'ca', n: 'Canada' },
		{ c: 'cc', n: 'Cocos (Keeling) Islands' },
		{ c: 'cd', n: 'DR Congo' },
		{ c: 'cf', n: 'Central African Republic' },
		{ c: 'cg', n: 'Republic of the Congo' },
		{ c: 'ch', n: 'Switzerland' },
		{ c: 'ci', n: "Côte d'Ivoire (Ivory Coast)" },
		{ c: 'ck', n: 'Cook Islands' },
		{ c: 'cl', n: 'Chile' },
		{ c: 'cm', n: 'Cameroon' },
		{ c: 'cn', n: 'China' },
		{ c: 'co', n: 'Colombia' },
		{ c: 'cr', n: 'Costa Rica' },
		{ c: 'cu', n: 'Cuba' },
		{ c: 'cv', n: 'Cape Verde' },
		{ c: 'cw', n: 'Curaçao' },
		{ c: 'cx', n: 'Christmas Island' },
		{ c: 'cy', n: 'Cyprus' },
		{ c: 'cz', n: 'Czechia' },
		{ c: 'de', n: 'Germany' },
		{ c: 'dj', n: 'Djibouti' },
		{ c: 'dk', n: 'Denmark' },
		{ c: 'dm', n: 'Dominica' },
		{ c: 'do', n: 'Dominican Republic' },
		{ c: 'dz', n: 'Algeria' },
		{ c: 'ec', n: 'Ecuador' },
		{ c: 'ee', n: 'Estonia' },
		{ c: 'eg', n: 'Egypt' },
		{ c: 'eh', n: 'Western Sahara' },
		{ c: 'er', n: 'Eritrea' },
		{ c: 'es', n: 'Spain' },
		{ c: 'et', n: 'Ethiopia' },
		{ c: 'eu', n: 'European Union' },
		{ c: 'fi', n: 'Finland' },
		{ c: 'fj', n: 'Fiji' },
		{ c: 'fk', n: 'Falkland Islands' },
		{ c: 'fm', n: 'Micronesia' },
		{ c: 'fo', n: 'Faroe Islands' },
		{ c: 'fr', n: 'France' },
		{ c: 'ga', n: 'Gabon' },
		{ c: 'gd', n: 'Grenada' },
		{ c: 'ge', n: 'Georgia' },
		{ c: 'gf', n: 'French Guiana' },
		{ c: 'gg', n: 'Guernsey' },
		{ c: 'gh', n: 'Ghana' },
		{ c: 'gi', n: 'Gibraltar' },
		{ c: 'gl', n: 'Greenland' },
		{ c: 'gm', n: 'Gambia' },
		{ c: 'gn', n: 'Guinea' },
		{ c: 'gp', n: 'Guadeloupe' },
		{ c: 'gq', n: 'Equatorial Guinea' },
		{ c: 'gr', n: 'Greece' },
		{ c: 'gs', n: 'South Georgia' },
		{ c: 'gt', n: 'Guatemala' },
		{ c: 'gu', n: 'Guam' },
		{ c: 'gw', n: 'Guinea-Bissau' },
		{ c: 'gy', n: 'Guyana' },
		{ c: 'hk', n: 'Hong Kong' },
		{ c: 'hm', n: 'Heard Island and McDonald Islands' },
		{ c: 'hn', n: 'Honduras' },
		{ c: 'hr', n: 'Croatia' },
		{ c: 'ht', n: 'Haiti' },
		{ c: 'hu', n: 'Hungary' },
		{ c: 'id', n: 'Indonesia' },
		{ c: 'ie', n: 'Ireland' },
		{ c: 'il', n: 'Israel' },
		{ c: 'im', n: 'Isle of Man' },
		{ c: 'in', n: 'India' },
		{ c: 'io', n: 'British Indian Ocean Territory' },
		{ c: 'iq', n: 'Iraq' },
		{ c: 'ir', n: 'Iran' },
		{ c: 'is', n: 'Iceland' },
		{ c: 'it', n: 'Italy' },
		{ c: 'je', n: 'Jersey' },
		{ c: 'jm', n: 'Jamaica' },
		{ c: 'jo', n: 'Jordan' },
		{ c: 'jp', n: 'Japan' },
		{ c: 'ke', n: 'Kenya', p: '254' },
		{ c: 'kg', n: 'Kyrgyzstan' },
		{ c: 'kh', n: 'Cambodia' },
		{ c: 'ki', n: 'Kiribati' },
		{ c: 'km', n: 'Comoros' },
		{ c: 'kn', n: 'Saint Kitts and Nevis' },
		{ c: 'kp', n: 'North Korea' },
		{ c: 'kr', n: 'South Korea' },
		{ c: 'kw', n: 'Kuwait' },
		{ c: 'ky', n: 'Cayman Islands' },
		{ c: 'kz', n: 'Kazakhstan' },
		{ c: 'la', n: 'Laos' },
		{ c: 'lb', n: 'Lebanon' },
		{ c: 'lc', n: 'Saint Lucia' },
		{ c: 'li', n: 'Liechtenstein' },
		{ c: 'lk', n: 'Sri Lanka' },
		{ c: 'lr', n: 'Liberia' },
		{ c: 'ls', n: 'Lesotho' },
		{ c: 'lt', n: 'Lithuania' },
		{ c: 'lu', n: 'Luxembourg' },
		{ c: 'lv', n: 'Latvia' },
		{ c: 'ly', n: 'Libya' },
		{ c: 'ma', n: 'Morocco' },
		{ c: 'mc', n: 'Monaco' },
		{ c: 'md', n: 'Moldova' },
		{ c: 'me', n: 'Montenegro' },
		{ c: 'mf', n: 'Saint Martin' },
		{ c: 'mg', n: 'Madagascar' },
		{ c: 'mh', n: 'Marshall Islands' },
		{ c: 'mk', n: 'North Macedonia' },
		{ c: 'ml', n: 'Mali' },
		{ c: 'mm', n: 'Myanmar' },
		{ c: 'mn', n: 'Mongolia' },
		{ c: 'mo', n: 'Macau' },
		{ c: 'mp', n: 'Northern Mariana Islands' },
		{ c: 'mq', n: 'Martinique' },
		{ c: 'mr', n: 'Mauritania' },
		{ c: 'ms', n: 'Montserrat' },
		{ c: 'mt', n: 'Malta' },
		{ c: 'mu', n: 'Mauritius' },
		{ c: 'mv', n: 'Maldives' },
		{ c: 'mw', n: 'Malawi' },
		{ c: 'mx', n: 'Mexico' },
		{ c: 'my', n: 'Malaysia' },
		{ c: 'mz', n: 'Mozambique' },
		{ c: 'na', n: 'Namibia' },
		{ c: 'nc', n: 'New Caledonia' },
		{ c: 'ne', n: 'Niger' },
		{ c: 'nf', n: 'Norfolk Island' },
		{ c: 'ng', n: 'Nigeria' },
		{ c: 'ni', n: 'Nicaragua' },
		{ c: 'nl', n: 'Netherlands' },
		{ c: 'no', n: 'Norway' },
		{ c: 'np', n: 'Nepal' },
		{ c: 'nr', n: 'Nauru' },
		{ c: 'nu', n: 'Niue' },
		{ c: 'nz', n: 'New Zealand' },
		{ c: 'om', n: 'Oman' },
		{ c: 'pa', n: 'Panama' },
		{ c: 'pe', n: 'Peru' },
		{ c: 'pf', n: 'French Polynesia' },
		{ c: 'pg', n: 'Papua New Guinea' },
		{ c: 'ph', n: 'Philippines' },
		{ c: 'pk', n: 'Pakistan' },
		{ c: 'pl', n: 'Poland' },
		{ c: 'pm', n: 'Saint Pierre and Miquelon' },
		{ c: 'pn', n: 'Pitcairn Islands' },
		{ c: 'pr', n: 'Puerto Rico' },
		{ c: 'ps', n: 'Palestine' },
		{ c: 'pt', n: 'Portugal' },
		{ c: 'pw', n: 'Palau' },
		{ c: 'py', n: 'Paraguay' },
		{ c: 'qa', n: 'Qatar' },
		{ c: 're', n: 'Réunion' },
		{ c: 'ro', n: 'Romania' },
		{ c: 'rs', n: 'Serbia' },
		{ c: 'ru', n: 'Russia' },
		{ c: 'rw', n: 'Rwanda' },
		{ c: 'sa', n: 'Saudi Arabia' },
		{ c: 'sb', n: 'Solomon Islands' },
		{ c: 'sc', n: 'Seychelles' },
		{ c: 'sd', n: 'Sudan' },
		{ c: 'se', n: 'Sweden' },
		{ c: 'sg', n: 'Singapore' },
		{ c: 'sh', n: 'Saint Helena, Ascension and Tristan da Cunha' },
		{ c: 'si', n: 'Slovenia' },
		{ c: 'sj', n: 'Svalbard and Jan Mayen' },
		{ c: 'sk', n: 'Slovakia' },
		{ c: 'sl', n: 'Sierra Leone' },
		{ c: 'sm', n: 'San Marino' },
		{ c: 'sn', n: 'Senegal' },
		{ c: 'so', n: 'Somalia' },
		{ c: 'sr', n: 'Suriname' },
		{ c: 'ss', n: 'South Sudan' },
		{ c: 'st', n: 'São Tomé and Príncipe' },
		{ c: 'sv', n: 'El Salvador' },
		{ c: 'sx', n: 'Sint Maarten' },
		{ c: 'sy', n: 'Syria' },
		{ c: 'sz', n: 'Eswatini (Swaziland)' },
		{ c: 'tc', n: 'Turks and Caicos Islands' },
		{ c: 'td', n: 'Chad' },
		{ c: 'tf', n: 'French Southern and Antarctic Lands' },
		{ c: 'tg', n: 'Togo' },
		{ c: 'th', n: 'Thailand' },
		{ c: 'tj', n: 'Tajikistan' },
		{ c: 'tk', n: 'Tokelau' },
		{ c: 'tl', n: 'Timor-Leste' },
		{ c: 'tm', n: 'Turkmenistan' },
		{ c: 'tn', n: 'Tunisia' },
		{ c: 'to', n: 'Tonga' },
		{ c: 'tr', n: 'Turkey' },
		{ c: 'tt', n: 'Trinidad and Tobago' },
		{ c: 'tv', n: 'Tuvalu' },
		{ c: 'tw', n: 'Taiwan' },
		{ c: 'tz', n: 'Tanzania' },
		{ c: 'ua', n: 'Ukraine' },
		{ c: 'ug', n: 'Uganda' },
		{ c: 'um', n: 'United States Minor Outlying Islands' },
		{ c: 'un', n: 'United Nations' },
		{ c: 'us', n: 'United States', p: '1' },
		{ c: 'uy', n: 'Uruguay' },
		{ c: 'uz', n: 'Uzbekistan' },
		{ c: 'va', n: 'Vatican City (Holy See)' },
		{ c: 'vc', n: 'Saint Vincent and the Grenadines' },
		{ c: 've', n: 'Venezuela' },
		{ c: 'vg', n: 'British Virgin Islands' },
		{ c: 'vi', n: 'United States Virgin Islands' },
		{ c: 'vn', n: 'Vietnam' },
		{ c: 'vu', n: 'Vanuatu' },
		{ c: 'wf', n: 'Wallis and Futuna' },
		{ c: 'ws', n: 'Samoa' },
		{ c: 'xk', n: 'Kosovo' },
		{ c: 'ye', n: 'Yemen' },
		{ c: 'yt', n: 'Mayotte' },
		{ c: 'za', n: 'South Africa' },
		{ c: 'zm', n: 'Zambia' },
		{ c: 'zw', n: 'Zimbabwe' }
	];
</script>

{#each countries as country}
	<Option value={country.c} selected={selected === country.c}>
		<img src="https://flagcdn.com/w20/{country.c}.png" width="16" height="12" alt={country.n} />
		{country.n}
	</Option>
{/each}
